<?php 
$this->headTitle('Beneficios Café de Villa Rica');        
$this->headMeta()->appendName('keywords', 'Café, Cafe, Café Tostado, Café Molido, Café arábigo, Café Grano Verde,Café Tostado, Taza de Café,cafe, cafe tostado, cafe en grano, cafe marca propia, licor de cafe, crema de cafe, licor, tienda en línea de café, coffee online store' );
$this->headMeta()->appendName('description', 'El café es consumido en gran medida no sólo por su sabor, sino por los efectos que tiene en los consumidores, debido a que contiene sustancias químicas que son estimulantes para las personas');
?>
<div id="content">
    <div id="content-inside">
        <div id="posts-full">

            <div class="single-post-item" id="post-87">
                <h2><a title="<?php echo  $this->post->getTitle() ?> | Café de Villa Rica" href="#"><?php echo  $this->post->getTitle() ?></a></h2>

                <div class="post-content post-content-full">
                    <?php echo  $this->post->getContent() ?>
                </div> <!-- post-content -->
            </div> <!-- post-item -->

        </div> <!-- posts-full -->
    </div>
</div> <!-- content -->