<?php 
$this->headTitle('Contactenos');        
$this->headMeta()->appendName('keywords', 'Café, Cafe, Café Tostado, Café Molido, Café arábigo, Café Grano Verde,Café Tostado, Taza de Café,cafe, cafe tostado, cafe en grano, cafe marca propia, licor de cafe, crema de cafe, licor, tienda en línea de café, coffee online store' );
$this->headMeta()->appendName('description', 'Si necesita más información o deseas realizar un pedido, por favor no dude en contactarnos utilizando el siguiente formulario.' );
?>
<div id="content">
    <div id="content-inside">
        <div id="posts-full">

            <div id="welcome" style="float: left;">
                    <h2>Contacte con nosotros</h2>
                    <p>Si necesita más información o deseas realizar un pedido, por favor no dude en contactarnos utilizando el siguiente formulario.</p>

                    <ul id="contact">
                        <li class="number"> (01)222-0400</li> 
                        <li class="email"><a title="Contactos" href="mailto:contactos@cafeomagua.com">contactos@cafeomagua.com</a></li>
                    </ul>

                    <ul id="hours">
                        <li class="primary-days">Lunes - Viernes</li>
                        <li class="primary-hours">8:00am - 6:00pm</li>                        
                    </ul>

                    <ul id="address">
                        <li class="street">Ubíquenos</li>
                        <li class="city">A.v los Angeles 412</li>
                        <li class="city">Urb. Santa Luzmila</li>
                        <li class="city">Comas - Lima</li>
                        
                    </ul>
                </div>
                <!-- start of page -->
                <div id="page" style="float: right; width: 400px;">
                    <?php if(!empty($this->mensajes)): ?>
                        <ul class="errorLabel">
                            <?php foreach($this->mensajes as $indice => $value):  ?>
                                <li>
                                <?php echo $indice . ': ' . $value ?>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    <?php endif; ?>
                    <?php if(empty($this->info)): ?>
                        <form class="form-horizontal" action="" method="post" name="contactform">
                            <div class="control-group">
                                <label class="control-label" for="inputEmail">Nombres: *</label>
                                <div class="controls">
                                  <input tabindex="1" type="text" name="name" id="name" style="width: 95%;"/>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="inputEmail">Email: *</label>
                                <div class="controls">
                                  <input tabindex="2" type="text" name="mail" id="mail" style="width: 95%;"/>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="inputEmail">Telefono:</label>
                                <div class="controls">
                                  <input tabindex="3" type="text" name="phone" id="phone"/>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="inputEmail">Mensaje:</label>
                                <div class="controls">
                                  <textarea tabindex="4" cols="30" rows="10" name="message" id="message" style="width: 95%;height: 80px;"></textarea>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="inputEmail"></label>
                                <div class="controls">
                                    <input tabindex="5" type="submit" name="submit" value="Enviar" class="btn" id="send" />
                                </div>
                            </div>
                        </form>
                    <?php else: ?>
                        <ul class="sussesLabel">
                            <?php foreach($this->info as $value):  ?>
                                <li>
                                <?php echo $value ?>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    <?php endif; ?>
                </div>
        </div> <!-- posts-full -->
    </div>
</div> <!-- content -->

